format = """
$username\
$directory\
$shell\
\n$character"""

add_newline = false

[shell]
disabled = false
style = "bg:8 fg:7"
format = '[ $indicator ]($style)'
fish_indicator = ' fish'
bash_indicator = ' bash'
unknown_indicator = ' ?'

[username]
show_always = true
style_user = "bg:4 fg:0"
style_root = "bg:3 fg:0"
format = '[▓▒░ 󰌽 $user ]($style)'

[directory]
style = "bg:7 fg:0"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = '[](4) '
error_symbol = '[](9) '
