#! /bin/sh

pgrep -x sxhkd > /dev/null || (sxhkd > /dev/null 2>&1 &)

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          2
bspc config window_gap            10
bspc config split_ratio           0.55
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        false
bspc config focus_follows_pointer true
bspc config normal_border_color   "#1e1e2e"
bspc config active_border_color   "#f9e2af"
bspc config focused_border_color  "#89b4fa"
bspc config presel_feedback_color "#89b4fa"

bspc rule -a floating state=floating
bspc rule -a org.gnome.FileRoller state=floating
bspc rule -a Galculator state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a zoom state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a doukutsu-rs.x86_64.elf state=floating
bspc rule -a steam_app_200900 state=floating
bspc rule -a mpv state=floating


#------#
# exec #
#------#
if [[ $1 -eq 0 ]]; then
	xsetroot -cursor_name left_ptr
	~/.fehbg
	/usr/bin/gnome-keyring-daemon -s
	(greenclip daemon > /dev/null &)
	(autocutsel &)
	(autocutsel -s PRIMARY &)
	(fastcompmgr -o 0.4 -r 12 -c -C > /dev/null &)
fi


#-------------#
# exec always #
#-------------#
polybar-launch.sh

