#!/bin/sh

pgrep -x sxhkd || (sxhkd &)

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          2
bspc config window_gap            10
bspc config split_ratio           0.55
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        false
bspc config focus_follows_pointer true
bspc config normal_border_color   "#1e1e2e"
bspc config active_border_color   "#f9e2af"
bspc config focused_border_color  "#89b4fa"
bspc config presel_feedback_color "#1e1e2e"

bspc rule -a floating state=floating
bspc rule -a *:YaST2 state=floating
bspc rule -a org.gnome.FileRoller state=floating
bspc rule -a Galculator state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a zoom state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a doukutsu-rs.x86_64.elf state=floating
bspc rule -a steam_app_200900 state=floating
bspc rule -a mpv state=pseudo_tiled


#------#
# exec #
#------#
if [[ $1 -eq 0 ]]; then
	xsetroot -cursor_name left_ptr
	~/.fehbg
	/usr/bin/gnome-keyring-daemon -s
	systemctl --user stop xfce4-notifyd
	(greenclip daemon &)
	(autocutsel &)
	(autocutsel -s PRIMARY &)
	#(fastcompmgr &)
	(dunst &)
fi


#-------------#
# exec always #
#-------------#
polybar-launch.sh

